import os
import json
import time
import random
import threading
from datetime import datetime
import requests
from bs4 import BeautifulSoup

class ReportGenerator:
    @staticmethod
    def generate_html_report(target, dorks_with_scores, output_filename="osint_report.html"):
        """Generates a professional HTML report of the generated dorks."""
        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>OSINT Dork Report - {target}</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #121212; color: #e0e0e0; margin: 0; padding: 20px; }}
                h1 {{ color: #4285f4; border-bottom: 2px solid #333; padding-bottom: 10px; }}
                .summary {{ background-color: #1e1e1e; padding: 15px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #34a853; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 20px; background-color: #1e1e1e; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }}
                th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #333; }}
                th {{ background-color: #2d2d2d; color: #4285f4; font-weight: bold; }}
                tr:hover {{ background-color: #2a2a2a; }}
                .weight-high {{ color: #34a853; font-weight: bold; }}
                .weight-med {{ color: #fbbc05; font-weight: bold; }}
                .weight-low {{ color: #ea4335; font-weight: bold; }}
                a {{ color: #4285f4; text-decoration: none; }}
                a:hover {{ text-decoration: underline; }}
                .footer {{ margin-top: 30px; text-align: center; color: #666; font-size: 0.9em; }}
            </style>
        </head>
        <body>
            <h1>OSINT Reconnaissance Report</h1>
            <div class="summary">
                <p><strong>Target:</strong> {target}</p>
                <p><strong>Generated At:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Total Dorks Generated:</strong> {len(dorks_with_scores)}</p>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>Dork Query</th>
                        <th>Brain Weight Score</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
        """
        for i, (dork, score) in enumerate(dorks_with_scores, 1):
            weight_class = "weight-low"
            if score > 15: weight_class = "weight-high"
            elif score > 5: weight_class = "weight-med"
            
            google_link = f"https://www.google.com/search?q={requests.utils.quote(dork)}"
            
            html_content += f"""
                    <tr>
                        <td>{i}</td>
                        <td><code>{dork}</code></td>
                        <td class="{weight_class}">{score:.2f}</td>
                        <td><a href="{google_link}" target="_blank">Search Google</a></td>
                    </tr>
            """
            
        html_content += """
                </tbody>
            </table>
            <div class="footer">
                Generated by Project-GDork Pro OSINT Engine
            </div>
        </body>
        </html>
        """
        
        try:
            with open(output_filename, 'w', encoding='utf-8') as f:
                f.write(html_content)
            return True, output_filename
        except Exception as e:
            return False, str(e)


class GHDBUpdater:
    @staticmethod
    def update_patterns(brain_instance):
        """Fetches latest GHDB patterns from a live repository."""
        import requests
        # Using a public repo known for hosting dork lists as a reliable live source
        url = "https://raw.githubusercontent.com/BullsEye0/google_dork_list/master/google_dorks.txt"
        count = 0
        try:
            response = requests.get(url, timeout=10)
            if response.status_code == 200:
                lines = response.text.split('\n')
                for line in lines:
                    pattern = line.strip()
                    if pattern and not pattern.startswith('#') and len(pattern) > 5:
                        if pattern not in brain_instance.knowledge['pattern_weights']:
                            brain_instance.knowledge['pattern_weights'][pattern] = 2.0
                            count += 1
                brain_instance.save_brain()
        except Exception as e:
            print(f"Error updating GHDB: {e}")
        return count


class LiveValidator:
    def __init__(self, brain_instance, callback=None):
        self.brain = brain_instance
        self.callback = callback
        self.running = False

    def validate_dorks(self, dorks_to_test):
        """Runs validation in a background thread."""
        self.running = True
        threading.Thread(target=self._worker, args=(dorks_to_test,), daemon=True).start()

    def _worker(self, dorks):
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        for dork in dorks:
            if not self.running:
                break
                
            try:
                # Add random sleep to prevent immediate blocking
                time.sleep(random.uniform(2.0, 5.0))
                
                url = f"https://www.google.com/search?q={requests.utils.quote(dork)}"
                if self.callback:
                    self.callback(f"Testing: {dork[:30]}...")
                    
                response = requests.get(url, headers=headers, timeout=10)
                if response.status_code == 200:
                    soup = BeautifulSoup(response.text, 'html.parser')
                    # Very simple heuristic: if result stats exist, we got hits.
                    stats = soup.find(id='result-stats')
                    if stats and " 0 " not in stats.text:
                        # Success!
                        if self.callback:
                            self.callback(f"SUCCESS (Hits found): {dork[:30]}...")
                        self.brain.register_success(dork)
                    else:
                        if self.callback:
                            self.callback(f"FAILED (No hits): {dork[:30]}...")
                        self.brain.register_failure(dork)
                elif response.status_code == 429:
                    if self.callback:
                        self.callback("WARNING: Google Rate Limit hit! Pausing validator.")
                    break
            except Exception as e:
                if self.callback:
                    self.callback(f"Error testing {dork[:20]}: {str(e)}")
                    
        self.running = False
        if self.callback:
            self.callback("Validation Complete.")
            
    def stop(self):
        self.running = False
